apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # this should be empty in static provisioning
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-077ab56b0a84495f3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs-static
  labels:
    purpose: efs-static-practice
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone : us-east-1c
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:        # docker run -v host-path:container-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static-svc
  labels:
    purpose: efs-static-practice
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-static-practice
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80