apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    purpose: rs-practice
    project: roboshop
    environment: dev
spec:
  replicas: 3
# these are the labels replicaset uses to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: rs-practice
      project: roboshop
      environment: dev
        
# this is pod definition. these are the pod labels
    template:
      metadata:
        labels:
          purpose: rs-practice
          project: roboshop
          environment: dev
        spec:
          containers:
          - name: nginx
            image: nginx:latest